### PR TITLE
Fix for snap.

### PR DESCRIPTION
**Pull request by gsilvapt**
* As suggested [here](https://snapcraft.io/docs/reference/plugins/source), there's a possibility to specify the branch and not the source tag only.
* This, hopefully, will help snapcraft know which branch to look for when building.
* source-type also specifies the type of version control system, which allegedly helps
resolving any urging issues from it.

### CODE REVIEW

**Comment by gsilvapt** [comment]
Forgot to pull first. Will reopen with proper changes.

**Comment by lapisdecor** [comment]
@gsilvapt snapcraft.io actually keeps making builds of every push to the non master branch. Maybe it's the default behavior?
I think it builds the right source but it keeps building every time a push is done. Also, I think it makes two builds by default: amd64 and arm.

**Comment by gsilvapt** [comment]
Could it be that the specified branch's yaml file is different than the source? I doubt this is a default feature but I can also ask. Nevertheless, I'll make the default `snapcraft.yaml` file the same as the one merged with this PR.

**Comment by lapisdecor** [comment]
@gsilvapt the git tag was done after I changed the yaml file. When you changed the yaml the new source creates a build that get's the code in the way you specified. I don't think the build process takes into account the old yaml file, since it creates a new build based on the new push.

**Pull request merged**
